# Generated by Django 4.2.1 on 2023-05-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
