# Generated by Django 4.2.1 on 2023-06-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_purchase_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='country',
            field=models.CharField(help_text='Enter where you are going to have estate', max_length=200),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(help_text='Enter owner name', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(choices=[('$', 'dollars'), ('€', 'euro'), ('D', 'dirhams')], help_text='units of estate', max_length=2),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(help_text='Enter type of estate', max_length=200),
        ),
    ]
